# Generated by Django 5.1.2 on 2024-11-10 12:50

import django.db.models.deletion
from django.db import migrations, models

def convert_category_to_string(apps, schema_editor):
    Product = apps.get_model('myapp', 'Product')
    Category = apps.get_model('myapp', 'Category')

    for product in Product.objects.all():
        # Find the category name by its ID
        category_name = product.category.name  # Assuming category is still a ForeignKey here
        # Update the product with the category name (string)
        product.category = category_name
        product.save()
        
class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_product_tags'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='myapp_produ_title_5f93c0_idx',
            old_name='myapp_produ_title_391dd3_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category'),
        ),
    ]
