# Generated by Django 5.1.2 on 2024-11-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_myapp_produ_title_391dd3_idx_myapp_produ_title_5f93c0_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Reviewer_email',
            new_name='reviewer_email',
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
