# Generated by Django 5.1.2 on 2024-11-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_reviewer_email_review_reviewer_email_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='myapp_produ_title_391dd3_idx',
            old_name='myapp_produ_title_5f93c0_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=255),
        ),
    ]
