# Generated by Django 5.1.2 on 2024-11-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_myapp_produ_title_5f93c0_idx_myapp_produ_title_391dd3_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.URLField(default='https://example.com/placeholder.jpg'),
        ),
    ]
