# Generated by Django 5.1.2 on 2024-11-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_product_category_alter_product_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer_name',
            field=models.CharField(max_length=255),
        ),
    ]
